defaults:
  - GradDiff

handler: SimNPO
method_args:
  delta: 2.0 # gamma in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  beta: 2.5
  alpha: 1.0
  gamma: 0.15 # npo_coeff in https://github.com/OPTML-Group/Unlearn-Simple/blob/main/TOFU/config/forget.yaml
  retain_loss_type: NLL

